cc_library(
  name = "common",
  srcs = glob([
      "common/*.cc",
      "string/*.cc",
      "system/*.cc",
      "time/*.cc"
      ],
      excludes = [
      "common/*_test.cc",
      "string/*_test.cc",
      "system/*_test.cc",
      "time/*_test.cc"
      ],
    )
    ],
  hdrs = [
    "common/*.h",
    "string/*.h",
    "system/*.h",
    "time/*.h"
    ],
)