load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

local_repository(
  name = "rules_cc",
  path = "bazel/rules_cc",
)

local_repository(
  name = "rules_java",
  path = "bazel/rules_java",
)

local_repository(
  name = "rules_proto",
  path = "bazel/rules_proto",
)

local_repository(
  name = "bazel_skylib",
  path = "bazel/bazel-skylib",
)

local_repository(
  name = "rules_python",
  path = "bazel/rules_python",
)

local_repository(
  name = "build_bazel_rules_apple",
  path = "bazel/rules_apple",
)

local_repository(
  name = "build_bazel_rules_swift",
  path = "bazel/rules_swift",
)

new_local_repository(
  name = "remote_java_tools_linux",
  path = "bazel/remote_java_tools_linux",
  build_file = "bazel/remote_java_tools_linux/BUILD",
)

new_local_repository(
  name = "remotejdk11_linux",
  path = "bazel/remotejdk11_linux",
  build_file = "bazel/remotejdk11_linux/BUILD.bazel",
)

new_local_repository(
  name = "com_google_abls",
  path = "bazel/com_google_abls",
  build_file = "bazel/com_google_abls/absl/BUILD.bazel",
)

new_local_repository(
  name = "gtest",
  path = "bazel/gtest",
  build_file = "bazel/gtest/BUILD.bazel",
)

new_local_repository(
  name = "com_google_protobuf",
  path = "bazel/grpc/third_party/protobuf",
  build_file = "bazel/grpc/third_party/protobuf/BUILD",
)

new_local_repository(
  name = "com_github_grpc_grpc",
  path = "bazel/grpc",
  build_file = "bazel/grpc/BUILD",
)

load("@com_github_grpc_grpc//bazel:grpc_deps.bzl", "grpc_deps")
grpc_deps()
load("@upb//bazel:workspace_deps.bzl", "upb_deps")
upb_deps()

